---
name_project: {{project_name}}

name_inventory: production
path_inventory: provision/ansible/inventories/sandbox/production
vagrant:
  limit: ''
  verbose: 'vvvv'
  sudo: true

servers:
  - name: 1.web.{{project_name}}.vm
    ip: 192.168.10.20
    box: ubuntu-14.4
    url: https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/14.04/ubuntu-14.04-amd64.box
    hostname: 1-web-{{project_name}}.vm
    ram: 512

  - name: 1.db.master.{{project_name}}.vm
    ip: 192.168.20.10
    box: ubuntu-14.4
    url: https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/14.04/ubuntu-14.04-amd64.box
    hostname: 1-db-master-{{project_name}}.vm
    ram: 512
